Repository KonferCA/SpurHacks, pull requests merged in 2025-04, with the labels that each got.

#21 create footer
  src/assets/index.ts
  src/assets/konfer_noicon.svg
  src/assets/logo_noicon.svg
  src/assets/spur_noicon.svg
  src/components/Footer.tsx
  src/components/index.ts
  src/pages/Landing.tsx
Labels: enhancement, frontend

#23 Create faq section
  package.json
  pnpm-lock.yaml
  src/components/index.ts
  src/components/sections/faq.section.tsx
  src/pages/Landing.tsx
Labels: enhancement, frontend

#28 Feat/18/navbar
  package.json
  pnpm-lock.yaml
  src/assets/index.ts
  src/assets/logos/icon_white.svg
  src/assets/mlh_banner.png
  src/components/Navbar/ExpandingMenu.tsx
  src/components/Navbar/Navbar.tsx
  src/components/index.ts
  src/components/sections/sponsorship.section.tsx
  src/pages/Landing.tsx
Labels: enhancement, frontend

#30 Fix sponsor section layout and data
  src/assets/data/sponsors.json
  src/components/sections/sponsorship.section.tsx
Labels: enhancement, frontend

#27 Create About2 section
  package.json
  pnpm-lock.yaml
  src/components/index.ts
  src/components/sections/about2.section.tsx
  src/pages/Landing.tsx
Labels: enhancement, frontend

#25 Optimization v1
  src/components/countup.tsx
  src/components/sections/hero.section.tsx
  src/components/sections/statistics.section.tsx
Labels: bug, frontend, refactor

#34 Fix countdown timer issue
  src/components/sections/hero.section.tsx
Labels: bug, frontend

#24 Create first about section
  package.json
  pnpm-lock.yaml
  src/assets/animations/knot_1.svg
  src/assets/animations/knot_2.svg
  src/assets/animations/knot_3.svg
  src/assets/animations/knot_4.svg
  src/assets/animations/knot_5.svg
  src/assets/animations/knot_6.svg
  src/assets/animations/knot_7.svg
  src/assets/animations/knot_8.svg
  src/assets/index.ts
  src/components/index.ts
  src/components/sections/about.section.tsx
  src/components/sections/about2.section.tsx
  src/pages/Landing.tsx
Labels: enhancement, frontend

#35 Fix navbar issues
  src/assets/index.ts
  src/assets/mlh_banner.png
  src/assets/mlh_banner.svg
  src/components/Navbar/ExpandingMenu.tsx
  src/components/Navbar/Navbar.tsx
Labels: bug, enhancement, frontend

#26 Centralize and conditionally load Spline component
  src/components/index.ts
  src/components/sections/faq.section.tsx
  src/components/sections/hero.section.tsx
  src/components/sections/statistics.section.tsx
  src/components/sections/updates.section.tsx
  src/components/spline/SplineTarget.tsx
  src/contexts/SplineContext.tsx
  src/contexts/index.ts
  src/main.tsx
  tsconfig.app.json
  vite.config.ts
Labels: bug, enhancement, frontend
