Repository KonferCA/SpurHacks, pull requests merged in 2025-05, with the labels that each got.

#46 Consolidate all strings to locale file
  src/components/Footer.tsx
  src/components/Navbar/ExpandingMenu.tsx
  src/components/Navbar/Navbar.tsx
  src/components/sections/about.section.tsx
  src/components/sections/about2.section.tsx
  src/components/sections/faq.section.tsx
  src/components/sections/hero.section.tsx
  src/components/sections/sponsorship.section.tsx
  src/components/sections/statistics.section.tsx
  src/components/sections/updates.section.tsx
  src/locales/en.json
  src/locales/index.ts
  tsconfig.app.json
  tsconfig.node.json
  vite.config.ts
Labels: enhancement, frontend, refactor

#47 Add initial set of content to the landing site
  src/components/sections/about.section.tsx
  src/components/sections/about2.section.tsx
  src/locales/en.json
Labels: frontend

#53 Refactor URLs from en.json and refactor all URLs in the site
  pnpm-lock.yaml
  src/components/Footer.tsx
  src/components/Navbar/Navbar.tsx
  src/components/sections/hero.section.tsx
  src/components/sections/spur.section.tsx
  src/components/sections/updates.section.tsx
  src/data/index.ts
  src/data/links.json
  src/locales/en.json
  src/locales/index.ts
Labels: frontend, refactor

#56 Fix FAQ animation stutter and layout shifts
  src/components/Navbar/Navbar.tsx
  src/components/sections/faq.section.tsx
  src/locales/index.ts
Labels: bug, frontend

#58 Create SocialMediaBar component
  src/components/Footer.tsx
  src/components/common/SocialMediaBar.tsx
  src/components/index.ts
  src/components/sections/hero.section.tsx
Labels: enhancement, frontend

#65 [add] anchor tag to mobile buttons
  src/components/sections/hero.section.tsx
Labels: URGENT, enhancement, frontend
